name: push-epubs-to-S3
on: 
  schedule:
  - cron:  '5 13 * * *'
jobs:
  get_reports:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout 
      uses: actions/checkout@v2
    - name: Get today's reports
      uses: addnab/docker-run-action@v3
      with:
        image: public.ecr.aws/i4f5a0p9/crpts:latest
        options:
            -e DATA_DOT_GOV_API_KEY=${{ secrets.DATA_DOT_GOV_API_KEY }}
            -e AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}
            -e AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          python main.py getfromday
